export const PROJECTS_LOADING = 'PROJECTS_LOADING';
export const ADD_PROJECTS = 'ADD_PROJECTS';
export const PROJECTS_FAILED = 'PROJECTS_FAILED';

export const PROJECTSAREA_LOADING = 'PROJECTSAREA_LOADING'; 
export const ADD_PROJECTSAREA = 'ADD_PROJECTSAREA';
export const PROJECTSAREA_FAILED = 'PROJECTSAREA_FAILED';

export const FOUNDERS_LOADING = 'FOUNDERS_LOADING';
export const ADD_FOUNDERS = 'ADD_FOUNDERS';
export const FOUNDERS_FAILED = 'FOUNDERS_FAILED';

export const STUDIO_LOADING = 'STUDIO_LOADING';
export const ADD_STUDIO = 'ADD_STUDIO';
export const STUDIO_FAILED = 'STUDIO_FAILED'; 